language: csharp
solution: Universe.Drawing.sln
mono:
  - latest
install:
  - nuget restore $TRAVIS_SOLUTION
  - printenv
script:
  - xbuild $TRAVIS_SOLUTION /t:Rebuild /p:Configuration=Release /verbosity:minimal
  - xbuild $TRAVIS_SOLUTION /t:Rebuild /p:Configuration=Debug   /verbosity:minimal
  - # bash -e test.sh
  - cd Universe.Drawing.Tests/bin/Release
  - mono Universe.Drawing.Tests.exe



  
  