language: csharp
solution: Universe.Drawing.sln 
mono:
  - latest
install:
  - nuget restore Universe.Drawing.sln 
  - printenv
script:
  - xbuild $TRAVIS_SOLUTION /t:Rebuild /p:Configuration=Release /verbosity:minimal
  - xbuild $TRAVIS_SOLUTION /t:Rebuild /p:Configuration=Debug   /verbosity:minimal
  - mono Universe.Drawing.Tests\bin\Release\Universe.Drawing.Tests.exe
  